Bump to ruby 2
[#89665398](https://www.pivotaltracker.com/story/show/89665398)

Signed-off-by: Caleb Miles <cmiles@pivotal.io>

diff --git a/packages/ruby_aws_cpi/packaging b/packages/ruby_aws_cpi/packaging
--- a/packages/ruby_aws_cpi/packaging
+++ b/packages/ruby_aws_cpi/packaging
@@ -1,6 +1,6 @@
 set -e
 
-tar xzf ruby_aws_cpi/yaml-0.1.5.tar.gz
+tar xzf ruby/yaml-0.1.5.tar.gz
 (
   set -e
   cd yaml-0.1.5
@@ -8,34 +8,28 @@ tar xzf ruby_aws_cpi/yaml-0.1.5.tar.gz
   make
   make install
 )
-if [[ $? != 0 ]] ; then
-  echo "Cannot install yaml"
-  exit 1
-fi
 
-tar xzf ruby_aws_cpi/ruby-1.9.3-p545.tar.gz
+tar xzf ruby/ruby-2.1.4.tar.gz
 (
   set -e
-  cd ruby-1.9.3-p545
-  LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=${BOSH_INSTALL_TARGET}
+  cd ruby-2.1.4
+  LDFLAGS="-Wl,-rpath -Wl,${BOSH_INSTALL_TARGET}" CFLAGS='-fPIC' ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=${BOSH_INSTALL_TARGET} --without-gmp
   make
   make install
 )
-if [[ $? != 0 ]] ; then
-  echo "Cannot install ruby"
-  exit 1
-fi
 
-tar zxvf ruby_aws_cpi/rubygems-2.1.11.tgz
+tar zxvf ruby/rubygems-2.3.0.tgz
+
 (
   set -e
-  cd rubygems-2.1.11
+  cd rubygems-2.3.0
 
-  ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
+  ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb --no-ri --no-rdoc
+
+  if [[ $? != 0 ]] ; then
+    echo "Cannot install rubygems"
+    exit 1
+  fi
 )
-if [[ $? != 0 ]] ; then
-  echo "Cannot install rubygems"
-  exit 1
-fi
 
-${BOSH_INSTALL_TARGET}/bin/gem install ruby_aws_cpi/bundler-1.8.2.gem --local --no-ri --no-rdoc
+${BOSH_INSTALL_TARGET}/bin/gem install ruby/bundler-1.6.3.gem --local --no-ri --no-rdoc
